# Generated by Django 4.2.30 on 2026-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=255)),
                ('banner_img', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
        migrations.CreateModel(
            name='CmsAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('subheading1', models.CharField(blank=True, default='', max_length=255)),
                ('subheading2', models.CharField(blank=True, default='', max_length=255)),
                ('subheading3', models.CharField(blank=True, default='', max_length=255)),
                ('desc1', models.TextField(blank=True, default='')),
                ('desc2', models.TextField(blank=True, default='')),
                ('desc3', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'cms_about',
            },
        ),
        migrations.CreateModel(
            name='CmsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_title', models.CharField(blank=True, default='', max_length=255)),
                ('email1', models.CharField(blank=True, default='', max_length=255)),
                ('email2', models.CharField(blank=True, default='', max_length=255)),
                ('phone1', models.CharField(blank=True, default='', max_length=20)),
                ('phone2', models.CharField(blank=True, default='', max_length=20)),
                ('fb_link', models.CharField(blank=True, default='', max_length=500)),
                ('twitter_link', models.CharField(blank=True, default='', max_length=500)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=500)),
                ('linkdin_link', models.CharField(blank=True, default='', max_length=500)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=500)),
                ('website_meta_keyword', models.TextField(blank=True, default='')),
                ('website_meta_desc', models.TextField(blank=True, default='')),
                ('gtag', models.TextField(blank=True, default='')),
                ('facebook_anylatics', models.TextField(blank=True, default='')),
                ('website_address', models.TextField(blank=True, default='')),
                ('website_logo', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'cms_setting',
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_enquiry',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('donation_img', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='DonationEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donation_enquiry',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=255)),
                ('about_events', models.TextField(blank=True, default='')),
                ('events_content', models.TextField(blank=True, default='')),
                ('events_img', models.CharField(blank=True, default='', max_length=255)),
                ('events_banner_img', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permission_type_id', models.IntegerField()),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'permission_type',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('permission_ids', models.TextField(blank=True, default='')),
                ('entry_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, default='', max_length=255)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=20)),
                ('email_id', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('access_level', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, default='', max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('testimonial_img', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=255)),
                ('volunteer_img', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'volunteer',
            },
        ),
    ]
